# skaffold.yaml
apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    push: false # Set to true if you're using a remote cluster
  tagPolicy:
    customTemplate:
      template: latest
  artifacts:
    - image: navasnoozy/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: /app


    - image: navasnoozy/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "src/**"
          dest: /app
        #   strip: "src/"
        # - src: "src/**/*.tsx"
        #   dest: /app/src
        #   strip: "src/"
        # - src: "src/**/*.js"
        #   dest: /app/src
        #   strip: "src/"
        # - src: "src/**/*.jsx"
        #   dest: /app/src
        #   strip: "src/"
        # - src: "public/**/*"
        #   dest: /app/public
        #   strip: "public/"


    - image: navasnoozy/products
      context: products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: /app


    # - image: navasnoozy/query
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    # - image: navasnoozy/moderation
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    # - image: navasnoozy/event-bus
    #   context: event-bus
    #   docker:
    #     dockerfile: Dockerfile



manifests:
  rawYaml:
    - ./infra/k8s/*.yaml

deploy:
  kubectl: {}

    # Add other K8s resources (services, config maps, etc.)




