apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: false # Set to true if you're using a remote cluster
  tagPolicy:
    customTemplate:
      template: latest
  artifacts:
    - image: navasnoozy/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: navasnoozy/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: navasnoozy/products
      context: products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: navasnoozy/query
    #   context: query
    #   docker:
    #     dockerfile: Dockerfile
    # - image: navasnoozy/moderation
    #   context: moderation
    #   docker:
    #     dockerfile: Dockerfile
    # - image: navasnoozy/event-bus
    #   context: event-bus
    #   docker:
    #     dockerfile: Dockerfile

manifests:
  rawYaml:
    - ./infra/k8s/*
    # Add other K8s resources (services, config maps, etc.)
