# skaffold.yaml
apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    push: false # Set to true if you're using a remote cluster
  tagPolicy:
    customTemplate:
      template: latest
  artifacts:
    - image: navasnoozy/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: /app
          - src: "dist/**/*.js"
            dest: /app/dist


    - image: navasnoozy/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: "src/**"
          dest: /app


    - image: navasnoozy/products
      context: products
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: /app






manifests:
  rawYaml:
    - ./infra/k8s/*.yaml #this for applying all common files of dev and production
    - ./infra/k8s-dev/*.yaml

deploy:
  kubectl: {}

    # Add other K8s resources (services, config maps, etc.)




