# infra/k8s/auth-depl.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      # initContainers:
      #   - name: wait-for-kafka
      #     image: busybox:1.28
      #     command: ['sh', '-c', 'until nslookup kafka.default.svc.cluster.local; do echo waiting for kafka; sleep 2; done; until nc -z kafka.default.svc.cluster.local 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
        - name: auth
          image: navasnoozy/auth:latest # Replace with your Docker image name
          imagePullPolicy: Never # Use 'Never' if you're using local Docker images with Minikube or Docker Desktop
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-uri
                  key: MONGO_URI   

            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"       # it will remove the kafka partitioning warning and use kafka default partitioning (new partitioning method), 

           

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth # This must match the labels on your pods/deployment
  ports:
    - name: auth
      protocol: TCP
      port: 3000 # Port that the service exposes internally
      targetPort: 3000 # Port your container is listening on (e.g., Express.js app)
