name: Build & Push Docker Image on Push

on:
  push:                                #  Trigger only on "push" events
    branches:                          #  Restrict to the main branch
      - main
    paths:                             #  Restrict workflow to only run if certain files change
      - "auth/**"                      #  Run only when files under auth/ folder are modified

jobs:
  build:
    runs-on: ubuntu-latest  # The virtual machine runner
                            # Locally: it's like running the build commands on your dev machine.

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # What it does: Authenticates to Docker Hub so pushes are allowed.
        # mandatory
        #  equivalent:
        #   bash> echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth:latest
        # What it does: Builds Docker image from repo context and pushes it.
        # Why it's mandatory: This is the core—build and push.
        # Real-world equivalent:
        #   bash> docker build -t youruser/yourrepo:pr-12 .
        #   bash> docker push youruser/yourrepo:pr-12
